import Head from "next/head";

import LoginForm from "./authentication/login";
import Layout from "@/components/Organisms/Layout";
import { Badge, Card, Col, Row, Table } from "react-bootstrap";
import TableBasic from "@/components/Organisms/Table";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LoginForm /> */}

      <Row className="mb-4">
        <Col md="4">
          <Card className="border-0">
            <Card.Body>
              <div className="d-grid gap-3">
                <div className="">
                  <span className="me-3">Receive Leads</span>
                  <Badge pill>7.25%</Badge>
                </div>
                <h2 className="fw-semibold mb-0">3.254</h2>
                <small className="text-muted">
                  Increase 250 from last month
                </small>
              </div>
            </Card.Body>
          </Card>
        </Col>
        <Col md="4">
          <Card className="border-top-0 border-bottom-0 border rounded-0">
            <Card.Body>
              <div className="d-grid gap-3">
                <div className="">
                  <span className="me-3">Locations</span>
                  <Badge bg="danger" pill>
                    120%
                  </Badge>
                </div>
                <h2 className="fw-semibold mb-0">3.254</h2>
                <small className="text-muted">
                  Decrease 13 from last month
                </small>
              </div>
            </Card.Body>
          </Card>
        </Col>
        <Col md="4">
          <Card className="border-0">
            <Card.Body>
              <div className="d-grid gap-3">
                <div className="">
                  <span className="me-3">Cost</span>
                  <Badge pill>8.5%</Badge>
                </div>
                <h2 className="fw-semibold mb-0">€2.302,5</h2>
                <small className="text-muted">
                  Increase €250,12 from last month
                </small>
              </div>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      <TableBasic title="Last 10 leads received" />
    </>
  );
}
